= Algorithm

== Overview

The SM2 cryptographic hash algorithm takes input of a message $$m$$ of length
$$l$$ (where $$l < 2^64$$), and after padding and iterative compression,
creates a hash value of 256-bits long.

Examples are provided in <<appendix-a>>.

== Padding

The following steps will pad any message $$m$$ to $$m'$$, where $$bitlen(m')$$
is a multiple of 512.

1. Input message $$m$$ has a length of $$l$$ bits.

2. Append a bit "1" to the end of the message $$m$$.

3. Append $$k$$ "0"s to the end of message $$m$$, where $$k$$ is the smallest
  non-negative number that satisfies $$l + 1 + k = 448 (mod 512)$$.

4. Append a 64-bit bit string $$L$$, where $$L = num2str(l, 64)$$.

For example, given a message `01100001 01100010 01100011`, its length $$l$$ is
24, after padding $$m'$$ will be:

[source]
----
            #1 Message m         #2  #3       #4 L
      /------------------------\ / /-----\ /---------\
m' =  01100001 01100010 01100011 1 00...00 00...011000
      \------------------------/   \-----/ \---------/
               24-bits            423-bits   64-bits
----

== Iterative Compression

=== Hashing Iterations

Inputs:

- $$m'$$, the padded message of $$m$$, composed of $$n$$ 512-bit blocks, where $$n = (l + k + 65) / 512$$
- $$IV$$, a 256-bit initialization vector

Output:

- $$V_n$$, the resulting hash value of $$m$$.


[source]
----
m' = B_0 || B_1 || ... || B_{n - 1}
V_0 = IV

for i = 0 to n - 1
  E_i = ME(B_i)
  V_{i + 1} = CF(V_i, E_i)
end

return V_n
----

Where,

- $$CF$$ is the compression function;
- $$ME$$ is the message expansion function;
- $$B_i$$ is the i-th block of the padded message $$m'$$.


=== Message Expansion Function $$ME$$

This steps expands each message block $$B_i$$ into bit string $$E_i$$ for the
compression function $$CF$$, where $$E$$ is made up of 132 words:
$$E_i = W_0 || ... || W_67 || W'_0 || ... || W'_63$$.

Inputs:

- $$B_i$$, the i-th message block of the padded message $$m'$$

Output:

- $$E_i$$, the result of the message expansion function

$$ME(B_i)$$ is defined as the following:

[source]
----
B_i = W_0 || ... || W_15

for j = 16 to 67
  W_j = P_1( W_{j - 16} xor W_{j - 9} xor (W_{j - 3} <<< 15) ) xor
          (W_{j - 13} <<< 7) xor
          W_{j - 6}
end

for j = 0 to 63
  W'_j = W_j xor W_{j + 4}
end

return E_i = W_0 || ... || W_67 || W'_0 || ... || W'_63
----


=== Compression Function $$CF$$

Inputs:

- $$V_i$$, the output value of the i-th iteration
- $$E_i$$, the expanded form of the i-th message block $$B_i$$

Variables:

- $$A, B, C, D, E, F, G, H$$, 32-bit registers
- $$SS1, SS2, TT1, TT2$$, 32-bit intermediate variables

Output:

- $$V_{i + 1}$$, the result of the compression function, where $$0 <= i <= n - 1$$.

$$CF(V_i, E_i)$$ is defined as the following:

[source]
----
A || B || C || D || E || F || G || H <- V_i
W_0 || ... || W_67 || W'_0 || ... || W'_63 <- E_i

for j = 0 to 63
  SS1 <- ((A <<< 12) + E + (T_j <<< (j mod 32))) <<< 7
  SS2 <- SS1 xor (A <<< 12)
  TT1 <- FF_j(A, B, C) + D + SS2 + W'_j
  TT2 <- GG_j(E, F, G) + H + SS1 + W_j
  D <- C
  C <- B <<< 9
  B <- A
  A <- TT1
  H <- G
  G <- F <<< 19
  F <- E
  E <- P_0(TT2)
end

return V_{i + 1} = (A || B || C || D || E || F || G || H) xor V_i
----

All 32-bit words used here are stored in big-endian format.

=== Hash Value

The final hash value $$y$$, of 256 bits long, is given by:

[source]
----
y = V_n
----
