
[bibliography]
= Bibliography

//== Normative

//bibliography::norm[]

//== Informative

//bibliography::info[]

++++
<reference anchor='SM2' target='http://www.oscca.gov.cn/UpFile/2010122214822692.pdf'>
  <front>
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<reference anchor='GMT-0003-2012' target='http://www.oscca.gov.cn/Column/Column_32.htm'>
  <front>
    <title>GM/T 0003-2012: Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date day='21' month='March' year='2012'/>
  </front>
</reference>

<reference anchor='GBT.32918.1-2016' target='http://www.sac.gov.cn/was5/web/search?channelid=97779&amp;templet=gjcxjg_detail.jsp&amp;searchword=STANDARD_CODE=%27GB/T%2032918.1-2016%27'>
  <front>
    <title>GB/T 32918.1-2016 Information Security Technology -- Public Key Cryptographic Algorithm SM2 Based On Elliptic Curves -- Part 1: General</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<reference anchor='GBT.32918.2-2016' target='http://www.sac.gov.cn/was5/web/search?channelid=97779&amp;templet=gjcxjg_detail.jsp&amp;searchword=STANDARD_CODE=%27GB/T%2032918.2-2016%27'>
  <front>
    <title>GB/T 32918.2-2016 Information Security Technology -- Public Key Cryptographic Algorithm SM2 Based On Elliptic Curves -- Part 2: Digital Signature Algorithm</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<reference anchor='GBT.32918.3-2016' target="http://www.sac.gov.cn/was5/web/search?channelid=97779&amp;templet=gjcxjg_detail.jsp&amp;searchword=STANDARD_CODE=%27GB/T%2032918.3-2016%27">
  <front>
    <title>GB/T 32918.3-2016 Information Security Technology -- Public Key Cryptographic Algorithm SM2 Based On Elliptic Curves -- Part 3: Key Exchange</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<reference anchor='GBT.32918.4-2016' target='http://www.sac.gov.cn/was5/web/search?channelid=97779&amp;templet=gjcxjg_detail.jsp&amp;searchword=STANDARD_CODE=%27GB/T%2032918.4-2016%27'>
  <front>
    <title>GB/T 32918.4-2016 Information Security Technology -- Public Key Cryptographic Algorithm SM2 Based On Elliptic Curves -- Part 4: Public Key Encryption Algorithm</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<!-- <reference anchor='GBT.32918.5-2017' target='http://www.sac.gov.cn/was5/web/search?channelid=97779&amp;templet=gjcxjg_detail.jsp&amp;searchword=STANDARD_CODE=%27GB/T%2032918.5-2017%27'> -->
<reference anchor='GBT.32918.5-2017' target='http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=728DEA8B8BB32ACFB6EF4BF449BC3077'>
  <front>
    <title>GB/T 32918.5-2017 Information Security Technology -- Public Key Cryptographic Algorithm SM2 Based On Elliptic Curves -- Part 5: Parameter Definition</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='12' month='May' year='2017'/>
  </front>
</reference>


<!-- <reference anchor='SM2-1' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_1.pdf'> -->
<reference anchor='SM2-1' target='http://www.oscca.gov.cn/UpFile/2010122214822692.pdf'>
  <front>
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves -- Part 1: General</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<!-- <reference anchor='SM2-2' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_2.pdf'> -->
<reference anchor='SM2-2' target='http://www.oscca.gov.cn/UpFile/2010122214822692.pdf'>
  <front>
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves -- Part 2: Digital Signature Algorithm</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<!-- <reference anchor='SM2-3' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_3.pdf'> -->
<reference anchor='SM2-3' target='http://www.oscca.gov.cn/UpFile/2010122214822692.pdf'>
  <front>
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves -- Part 3: Key Exchange Protocol</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<reference anchor='SM2-4' target='http://www.oscca.gov.cn/UpFile/2010122214822692.pdf'>
<!-- <reference anchor='SM2-4' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_4.pdf'> -->
  <front>
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves -- Part 4: Public Key Encryption Algorithm</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>

    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<!-- <reference anchor='SM2-5' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM2_5.pdf'> -->
<reference anchor='SM2-5' target='http://www.oscca.gov.cn/UpFile/2010122214836668.pdf'>
  <front>
    <!--<title>Public Key Cryptographic Algorithm SM2 Recommended Elliptic Curves Parameters</title>-->
    <title>Public Key Cryptographic Algorithm SM2 Based on Elliptic Curves -- Part 5: Parameter definitions</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='December' year='2010'/>
  </front>
</reference>

<reference anchor='GMT-0006-2012' target='http://www.oscca.gov.cn/Column/Column_32.htm'>
  <front>
    <title>GM/T 0006-2012: Cryptographic Application Identifier Criterion Specification</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date day='21' month='March' year='2012'/>
  </front>
</reference>

<reference anchor='SM2-SigSecurity' target='https://link.springer.com/chapter/10.1007/978-3-319-27152-1_7'>
  <front>
    <title>Security of the SM2 Signature Scheme Against Generalized Key Substitution Attacks</title>
<!-- International Conference on Research in Security Standardisation
Security Standardisation Research pp 140-153 -->
    <author initials="Z." surname="Zhang" fullname="Zhenfeng Zhang">
      <organization>Laboratory of Trusted Computing and Information Assurance, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>zfzhang@tca.iscas.ac.cn</email>
        <uri>http://tca.iscas.ac.cn</uri>
      </address>
    </author>
    <author initials="K." surname="Yang" fullname="Kang Yang">
      <organization>Laboratory of Trusted Computing and Information Assurance, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>yangkang@tca.iscas.ac.cn</email>
        <uri>http://tca.iscas.ac.cn</uri>
      </address>
    </author>
    <author initials="J." surname="Zhang" fullname="Jiang Zhang">
      <organization>State Key Laboratory of Cryptology</organization>
      <address>
        <postal>
          <street>P.O. Box 5159</street>
          <city>Beijing</city>
          <code>100878</code>
          <country>People's Republic of China</country>
        </postal>
        <email>jiangzhang09@gmail.com</email>
      </address>
    </author>
    <author initials="C." surname="Chen" fullname="Cheng Chen">
      <organization>Laboratory of Trusted Computing and Information Assurance, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>chencheng@tca.iscas.ac.cn</email>
        <uri>http://tca.iscas.ac.cn</uri>
      </address>
    </author>
    <date day='9' month='December' year='2015'/>
  </front>
</reference>

<reference anchor='SM2-Template' target='https://doi.org/10.1109/CIS.2014.66'>
  <front>
    <title>A Novel Template Attack on wNAF Algorithm of ECC</title>
<!--2014 Tenth International Conference on Computational Intelligence and Security, Kunming, 2014, pp. 671-675.-->
    <author initials="Z." surname="Zhang" fullname="Zhenbin Zhang">
      <organization>Institute of Microelectronics, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <author initials="L." surname="Wu" fullname="Liji Wu">
      <organization>Institute of Microelectronics, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <author initials="Z." surname="Mu" fullname="Zhaoli Mu">
      <organization>Institute of Microelectronics, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Beijing</city>
          <code>100084</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.tsinghua.edu.cn</uri>
      </address>
    </author>
    <author initials="X." surname="Zhang" fullname="Xiangmin Zhang">
      <organization>Datang Microelectronics Technololgy Co., Ltd</organization>
      <address>
        <postal>
          <city>Beijing</city>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.dmt.com.cn</uri>
      </address>
    </author>
    <date month='November' year='2014'/>
  </front>
</reference>

<reference anchor='SM2-KEP-Comments' target='https://dx.doi.org/10.1007/978-3-642-25513-7_12'>
  <front>
    <title>Comments on the SM2 Key Exchange Protocol</title>
<!--bookTitle="Cryptology and Network Security: 10th International Conference, CANS 2011, Sanya, China, December 10-12, 2011. Proceedings",-->
    <author initials="X." surname="Xu" fullname="Jing Xu">
      <organization>State Key Laboratory of Information Security, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>xujing@is.iscas.ac.cn</email>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="D." surname="Feng" fullname="Dengguo Feng">
      <organization>State Key Laboratory of Information Security, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <date day='10' month='December' year='2011'/>
  </front>
</reference>

<reference anchor='SM2-DSA-Nonces' target='https://dx.doi.org/10.1007/978-3-319-12087-4_22'>
  <front>
    <title>Partially Known Nonces and Fault Injection Attacks on SM2 Signature Algorithm</title>
<!--Information Security and Cryptology: 9th International Conference, Inscrypt 2013, Guangzhou, China, November 27-30, 2013, Revised Selected Papers-->
    <author initials="M." surname="Liu" fullname="Mingjie Liu">
      <organization>Beijing International Center for Mathematical Research, Peking University</organization>
      <address>
        <postal>
          <street>No. 5 Yiheyuan Road Haidian District</street>
          <city>Beijing</city>
          <code>100871</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.bicmr.org</uri>
      </address>
    </author>
    <author initials="J." surname="Chen" fullname="Jiazhe Chen">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.itsec.gov.cn</uri>
      </address>
    </author>
    <author initials="H." surname="Li" fullname="Hexin Li">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.itsec.gov.cn</uri>
      </address>
    </author>
    <date day='27' month='November' year='2013'/>
  </front>
</reference>

<reference anchor='SM2-DSA-Nonces2' target='https://doi.acm.org/10.1145/2714576.2714587'>
  <front>
    <title>Mind Your Nonces Moving: Template-Based Partially-Sharing Nonces Attack on SM2 Digital Signature Algorithm</title>
<!--Proceedings of the 10th ACM Symposium on Information, Computer and Communications Security (ASIA CCS '15)-->
    <author initials="J." surname="Chen" fullname="Jiazhe Chen">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <email>jiazhechen@gmail.com</email>
        <uri>http://www.itsec.gov.cn</uri>
      </address>
    </author>
    <author initials="M." surname="Liu" fullname="Mingjie Liu">
      <organization>Beijing Research Institute of Telemetry, China Aerospace Science and Technology Corporation</organization>
      <address>
        <postal>
          <street>1 Nan Da Hong Men Lu, Fengtai Qu</street>
          <city>Beijing</city>
          <code>100194</code>
          <country>People's Republic of China</country>
        </postal>
        <email>liumj9705@gmail.com</email>
        <uri>http://www.spacechina.com</uri>
      </address>
    </author>
    <author initials="H." surname="Shi" fullname="Hongsong Shi">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.itsec.gov.cn</uri>
        <!--<email>unknown</email>-->
      </address>
    </author>
    <author initials="H." surname="Li" fullname="Hexin Li">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <email>lihx@secemail.cn</email>
        <uri>http://www.itsec.gov.cn</uri>
      </address>
    </author>
    <date day='27' month='November' year='2015'/>
  </front>
</reference>

<reference anchor='SM2-DSA-Lattice' target='https://doi.org/10.1007/978-3-319-29814-6_6'>
  <front>
    <title>Practical Lattice-Based Fault Attack and Countermeasure on SM2 Signature Algorithm</title>
<!--Information and Communications Security. ICICS 2015. Lecture Notes in Computer Science, vol 9543. Springer, Cham-->
    <author initials="W." surname="Cao" fullname="Weiqiong Cao">
      <organization>Trusted Computing and Information Assurance Laboratory, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="J." surname="Feng" fullname="Jingyi Feng">
      <organization>Trusted Computing and Information Assurance Laboratory, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="S." surname="Zhu" fullname="Shaofeng Zhu">
      <organization>Trusted Computing and Information Assurance Laboratory, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="H." surname="Chen" fullname="Hua Chen">
      <organization>Trusted Computing and Information Assurance Laboratory, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>Trusted Computing and Information Assurance Laboratory, Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>4# South Fourth Street, Zhong Guan Cun</street>
          <city>Beijing</city>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://english.is.cas.cn</uri>
      </address>
    </author>
    <author initials="X." surname="Han" fullname="Xucang Han">
      <organization>Beijing Key Laboratory of RFID Chip Test Technology, CEC Huada Electronic Design Co., Ltd</organization>
      <address>
        <postal>
          <street>Building C, CEC Network Security and Information Technology Base, South Region of Future Science And Technology Park, Beiqijia county, Changping District</street>
          <city>Beijing</city>
          <code>102209</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.hed.com.cn</uri>
      </address>
    </author>
    <author initials="X." surname="Zheng" fullname="Xiaoguang Zheng">
      <organization>Beijing Key Laboratory of RFID Chip Test Technology, CEC Huada Electronic Design Co., Ltd</organization>
      <address>
        <postal>
          <street>Building C, CEC Network Security and Information Technology Base, South Region of Future Science And Technology Park, Beiqijia county, Changping District</street>
          <city>Beijing</city>
          <code>102209</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.hed.com.cn</uri>
      </address>
    </author>
    <date month='November' year='2016'/>
  </front>
</reference>

<reference anchor='NIST.SP.800-56Ar2' target='http://dx.doi.org/10.6028/NIST.SP.800-56Ar2'>
  <front>
    <title>SP 800-56Ar2 Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography</title>
    <author initials="B." surname="Barker" fullname="Elaine B. Barker">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="L." surname="Chen" fullname="Lily Chen">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="A." surname="Roginsky" fullname="Allen Roginsky">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="M." surname="Smid" fullname="Miles Smid">
      <organization>Orion Security Solutions, Inc.</organization>
      <address>
        <postal>
          <street>1489 Chain Bridge Road</street>
          <street>Suite 300</street>
          <city>McLean</city>
          <region>VA</region>
          <code>22101</code>
          <country>United States</country>
        </postal>
        <uri>http://www.orionsecuritysolutions.com</uri>
      </address>
    </author>
    <date month='May' year='2013'/>
  </front>
</reference>


<reference anchor='GBT.32905-2016' target='www.gb688.cn/bzgk/gb/newGbInfo?hcno=45B1A67F20F3BF339211C391E9278F5E'>
<!--http://www.sac.gov.cn/SACSearch/search?channelid=97779&templet=gjcxjg_detail.jsp&searchword=STANDARD_CODE=%27GB/T%2032905-2016%27 -->
  <front>
    <title>GB/T 32905-2016: Information security techniques -- SM3 cryptographic hash algorithm</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<reference anchor='OSCCA' target='http://www.oscca.gov.cn'>
  <front>
    <title>Organization of State Commercial Administration of China</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='May' year='2017'/>
  </front>
</reference>

<reference anchor='SEC1' target='http://www.secg.org/SEC1-Ver-1.0.pdf'>
  <front>
    <title>SEC 1: Elliptic Curve Cryptography</title>
    <author>
      <organization>Standards for Efficient Cryptography Group</organization>
    </author>
    <date month='September' year='2010'/>
  </front>
</reference>

<reference anchor='ISO.IEC.14888-3' target='https://www.iso.org/standard/70631.html'>
  <front>
    <title>ISO/IEC 14888-3:2016-03 -- Information technology -- Security techniques -- Digital signatures with appendix -- Part 3: Discrete logarithm based mechanisms</title>
    <author>
      <organization>International Organization for Standardization</organization>
      <address>
        <postal>
          <street>BIBC II</street>
          <street>Chemin de Blandonnet 8</street>
          <street>CP 401</street>
          <city>Vernier</city>
          <region>Geneva</region>
          <code>1214</code>
          <country>Switzerland</country>
        </postal>
        <phone>+41 22 749 01 11</phone>
        <email>central@iso.org</email>
        <uri>https://www.iso.org/</uri>
      </address>
    </author>
    <date day='04' month='September' year='2017'/>
  </front>
</reference>

<reference anchor='BOTAN' target='https://botan.randombit.net'>
  <front>
    <title>Botan: Crypto and TLS for C++11</title>
    <author initials="J. E." surname="Lloyd" fullname="Jack E. Lloyd">
      <organization>Botan Project</organization>
      <address>
        <postal>
          <street></street>
          <country>United States of America</country>
        </postal>
        <email>jack@randombit.net</email>
        <uri>https://botan.randombit.net</uri>
      </address>
    </author>
    <date day='31' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='OPENSSL' target='https://www.openssl.org'>
  <front>
    <title>OpenSSL: Cryptography and SSL/TLS Toolkit</title>
    <author>
      <organization>OpenSSL Software Foundation</organization>
      <address>
        <postal>
          <street>20-22 Wenlock Road</street>
          <city>London</city>
          <code>N1 7GU</code>
          <country>United Kingdom</country>
        </postal>
        <phone>+44 17 8550 8015</phone>
        <email>info@opensslfoundation.org</email>
        <uri>https://www.openssl.org</uri>
      </address>
    </author>
    <date day='31' month='October' year='2017'/>
  </front>
</reference>

<reference anchor="RFC2119" target="https://www.rfc-editor.org/info/rfc2119">
  <front>
    <title>Key words for use in RFCs to Indicate Requirement Levels</title>
    <author initials="S." surname="Bradner" fullname="S. Bradner">
      <organization/>
    </author>
    <date year="1997" month="March"/>
    <abstract>
      <t>In many standards track documents several words are used to signify the requirements in the specification.  These words are often capitalized. This document defines these words as they should be interpreted in IETF documents.  This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.</t>
    </abstract>
  </front>
  <seriesInfo name="BCP" value="14"/>
  <seriesInfo name="RFC" value="2119"/>
  <seriesInfo name="DOI" value="10.17487/RFC2119"/>
</reference>
++++
